#!/bin/sh
#
# Copyright IBM Corp. 2006, 2008
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License (version 2 only)
# as published by the Free Software Foundation.
#
# setup_zfcp
#
# System Loader script to set zfcp devices online on s390
#
#
# Author(s): Michael Loehr   (mloehr@de.ibm.com)
#            Christof Schmitt (christof.schmitt@de.ibm.com)
#
# $Id: setup_zfcp,v 1.2 2008/05/16 07:35:53 schmichr Exp $
#

wait_for_devices()
{
    if [ -x /sbin/udevsettle ]; then
	/sbin/udevsettle
    else
	/sbin/udevstart
    fi
}

if [ $# -ne 3 ]; then
    echo "Invalid number of parameters."
    exit 1
fi

BUSID=$1
WWPN=$2
LUN=$3

cd /sys/bus/ccw/drivers/zfcp/$BUSID/
echo 1 >online
usleep 500000
echo $WWPN >port_add
usleep 500000
cd $WWPN
echo $LUN >unit_add
usleep 500000

wait_for_devices

#evms_activate
#usleep 500000
